#!/usr/bin/env python3
"""Module demonstrating the use of an asynchronous comprehension
    with an async generator."""

import asyncio
from typing import List

# Importing the async_generator function
task_0_function = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Returns a list of 10 random floats using an asynchronous
       list comprehension.

    This function gathers random numbers generated by an
    async generator, ensuring efficient, non-blocking execution.
    """
    # Collects numbers asynchronously
    return [i async for i in task_0_function()]
